#!/usr/bin/env php
<?php
//declare(ticks = 1);
require __DIR__.'/vendor/autoload.php';

define("HOME", __DIR__);

date_default_timezone_set("PRC");
use Workerman\Worker;
$send_count = 0;
$send_count2 = 0;

// Create a Websocket server
$ws_worker = new Worker("tcp://0.0.0.0:9997");

// 4 processes
$ws_worker->count = 1;

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
    echo "New connection\n";
};

// Emitted when data received
$ws_worker->onMessage = function($connection, $data)
{
    global $ws_worker,$send_count,$send_count2;
    //$current_process_id = get_current_processid();

    // Send hello $data
    //$connection->send('hello ' . $data);
    ob_start();
    $path[] = HOME . "/cache/tcp/*";
    while (count($path) != 0) {
        $v = array_shift($path);
        foreach (glob($v) as $item) {
            if (is_file($item)) {
                $send_count++;
                $content = file_get_contents($item);
                foreach ($ws_worker->connections as $c) {
                    $c->send($content."\r\n\r\n\r\n");
                    $send_count2++;
                }
                file_put_contents(HOME."/logs/tcp", $send_count.":".$send_count2);

                unlink($item);
            }
        }
    }
    $debug = ob_get_contents();
    ob_end_clean();

    if ($debug) {
        echo $debug;
    }

    unset($debug, $recv_msg);
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

$ws_worker->onWorkerStart = function(){
    //file_put_contents(HOME."/tcp.pid",get_current_processid()."   ", FILE_APPEND);
};
// Run worker
Worker::runAll();
