#!/usr/bin/env php
<?php
//declare(ticks = 1);
require __DIR__.'/vendor/autoload.php';

define("HOME", __DIR__);

date_default_timezone_set("PRC");
use Workerman\Worker;


$host = "0.0.0.0";
$port = 9997;

foreach ($argv as $item) {
    if ($item == "--host")
        $host = $item;
    if ($item == "--port")
        $port = $item;
}

// Create a Websocket server
$ws_worker = new Worker("websocket://".$host.":".$port);

// 4 processes
$ws_worker->count = 1;

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
    echo "New connection\n";
};


// Emitted when data received
$ws_worker->onMessage = function($connection, $data)
{
    global $ws_worker;
    //$current_process_id = get_current_processid();

    // Send hello $data
    //$connection->send('hello ' . $data);
    ob_start();
    $path[] = HOME . "/cache/websocket/*";
    while (count($path) != 0) {
        $v = array_shift($path);
        foreach (glob($v) as $item) {
            if (is_file($item)) {
                $content = file_get_contents($item);
                if (!$content) {
                    continue;
                }
                foreach ($ws_worker->connections as $c) {
                    $c->send($content);
                }
                unlink($item);
            }
        }
    }
    $debug = ob_get_contents();
    ob_end_clean();

    if ($debug) {
        echo $debug;
    }

    unset($debug, $recv_msg);
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};
$ws_worker->onWorkerStart = function(){
  //file_put_contents(HOME."/websocket.pid",get_current_processid()."   ", FILE_APPEND);
};

// Run worker
Worker::runAll();
