#!/usr/bin/env php
<?php
//declare(ticks = 1);
require __DIR__.'/vendor/autoload.php';

define("HOME", __DIR__);

date_default_timezone_set("PRC");
use Workerman\Worker;

// Create a Websocket server
$ws_worker = new Worker("websocket://0.0.0.0:9998");

// 4 processes
$ws_worker->count = 4;

// Emitted when new connection come
$ws_worker->onConnect = function($connection)
{
    echo "New connection\n";
};

// Emitted when data received
$ws_worker->onMessage = function($connection, $data)
{
    global $ws_worker;
    // Send hello $data
    //$connection->send('hello ' . $data);
    ob_start();
    $path[] = HOME . "/cache/websocket/*";
    while (count($path) != 0) {
        $v = array_shift($path);
        foreach (glob($v) as $item) {
            if (is_file($item)) {
                $content = file_get_contents($item);
                foreach ($ws_worker->connections as $c) {
                    $c->send($content);
                }
                unlink($item);
            }
        }
    }
    $debug = ob_get_contents();
    ob_end_clean();

    if ($debug) {
        echo $debug;
    }

    unset($debug, $recv_msg);
};

// Emitted when connection closed
$ws_worker->onClose = function($connection)
{
    echo "Connection closed\n";
};

// Run worker
Worker::runAll();
