#!/usr/bin/env php
<?php
//declare(ticks = 1);
require __DIR__.'/vendor/autoload.php';

$dir = __DIR__;
if (strpos($dir, "/cygdrive/") !== false) {
	$dir = str_replace("/cygdrive/", "", $dir);
	$pan = substr($dir, 0, 1);
	$dir = substr($dir, 1);
	$dir = strtoupper($pan) . ":" . $dir;
}

define("HOME", $dir);

date_default_timezone_set("PRC");

use Symfony\Component\Console\Application;

$debug = false;
foreach ($argv as $item) {
    if (strpos($item, "debug") !== false) {
		$debug = true;
    }

    if (strpos($item, "restart") !== false) {
        $winfo  = \Wing\Library\Worker::getWorkerProcessInfo();
        $debug  = $winfo["debug"];
    }
}

$str_argv = '';
for ($i = 1; $i < $argc; $i++) {
    $str_argv .= ' '.$argv[$i];
}

$file_name = str_replace(__DIR__, "", __FILE__);
$file_name = trim($file_name, "/");
$file_name = trim($file_name, "\\");

$command_line = 'php '.$file_name.' '.$str_argv;
define("WING_COMMAND_LINE", $command_line);
//echo $command_line,"\r\n";

if ($debug) {
	define("WING_DEBUG", true);
} else {
	define("WING_DEBUG", false);
}


try {

    $application = new Application("wing-binlog");
    $application->setCatchExceptions(true);

    $commands = [
        \Wing\Command\ServerStart::class,
        \Wing\Command\ServerStop::class,
        \Wing\Command\ServerVersion::class,
        \Wing\Command\ServerStatus::class,
        \Wing\Command\Help::class,
        \Wing\Command\ServerRestart::class
    ];
    foreach ($commands as $command) {
        $application->add(new $command);
    }

    $application->run();
} catch (\Exception $e){
    var_dump($e);
}